import { Theme } from "@/types/Theme";

// Add path of themes file to tailwind.config.ts like as below

// content: [
//   "./pages/**/*.{js,ts,jsx,tsx,mdx}",
//   "./components/**/*.{js,ts,jsx,tsx,mdx}",
//   "./app/**/*.{js,ts,jsx,tsx,mdx}",
//   "./lib/**/*.{js,ts,jsx,tsx,mdx}",
// ],

export const themes: Theme[] = [
  {
    id: 1,
    color: "bg-white",
    text: "text-black",
    name: "Air White",
    linkStyle: "rounded-md",
    boxColor: "bg-red-200",
    shopBox: "rounded-md",
    hover: "",
    embosedBox: false,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-gray-200",
  },
  {
    id: 2,
    color: "bg-[#000957]", // Deep Blue
    text: "text-white", // White text for contrast
    shopBox: "rounded-md",
    name: "Blue Horizon",
    linkStyle: "rounded-md", // Rounded link style
    boxColor: "bg-[#344CB7]", // Lighter Blue
    hover: "",
    embosedBox: true,
    embosedBoxColor: "bg-[#FFEB00]", // Yellow for embossed effect
    tabColor: "bg-blue-600",
  },
  {
    id: 3,
    color: "bg-gradient-to-t from-indigo-500 via-purple-500 to-pink-500",
    text: "text-black",
    name: "Purple Pie",
    shopBox: "rounded-3xl",
    linkStyle: "rounded-full",
    boxColor: "bg-orange-300",
    hover: "hover:scale-105 ease-in-out",
    embosedBox: false,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-purple-400",
  },
  {
    id: 4,
    color: "bg-gradient-to-t from-[#16C47F] via-[#FFD65A] to-[#FF9D23]",
    text: "text-black",
    name: "Tropical Vibes",
    shopBox: "rounded-xl",
    linkStyle: "rounded-md",
    boxColor: "bg-[#FFD65A]",
    hover: "",
    embosedBox: true,
    embosedBoxColor: "bg-[#FF9D23]",
    tabColor: "bg-[#FFD65A]",
  },
  {
    id: 5,
    color: "bg-gradient-to-t from-orange-500 via-green-500 to-red-500",
    text: "text-white",
    name: "Traffic Lights",
    linkStyle: "rounded-3xl",
    shopBox: "rounded-3xl",
    boxColor: "bg-pink-500",
    hover: "",
    embosedBox: true,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-red-500",
  },
  {
    id: 6,
    color: "bg-gradient-to-b from-blue-800 via-blue-500 to-green-500",
    text: "text-slate-900",
    name: "Blue Sky",
    linkStyle: "rounded-md",
    shopBox: "rounded-md",
    boxColor: "bg-lime-200",
    hover: "",
    embosedBox: false,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-blue-600",
  },
  {
    id: 7,
    color: "bg-gradient-to-t from-lime-500 via-indigo-700 to-amber-500",
    text: "text-white",
    name: "Soft Horizon",
    linkStyle: "rounded-xl",
    shopBox: "rounded-3xl",
    boxColor: "bg-purple-300",
    hover: "",
    embosedBox: true,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-lime-400",
  },
  {
    id: 8,
    color: "bg-gradient-to-t from-gray-800 to-emerald-500",
    text: "text-white",
    name: "Tinted Lake",
    linkStyle: "rounded-full bg-transparent border",
    shopBox: "rounded-3xl border",
    boxColor: "",
    hover: "hover:bg-white hover:text-emerald-800",
    embosedBox: false,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-emerald-400",
  },
  {
    id: 9,
    color: "bg-gradient-to-t from-pink-600 via-pink-500 to-pink-300",
    text: "text-white",
    name: "Cotton Candy",
    linkStyle: "rounded-lg",
    shopBox: "rounded-lg",
    boxColor: "bg-indigo-400",
    hover: "",
    embosedBox: false,
    embosedBoxColor: "bg-yellow-800",
    tabColor: "bg-pink-400",
  },
  {
    id: 10,
    color: "bg-[#f8d210]",
    text: "text-black",
    name: "Tropical Burst",
    linkStyle: "rounded-md",
    shopBox: "rounded-md",
    boxColor: "bg-[#f51720]",
    hover: "",
    embosedBox: true,
    embosedBoxColor: "bg-[#fa26a0]",
    tabColor: "bg-yellow-400",
  },
  {
    id: 11,
    color: "bg-gradient-radial from-[#3d550c] via-[#81b622] to-[#ecf87f]",
    text: "text-black",
    name: "Lush Green",
    linkStyle: "rounded-lg",
    shopBox: "rounded-md",
    boxColor: "bg-[#59981a]",
    hover: "hover:top-1 hover:left-1",
    embosedBox: true,
    embosedBoxColor: "bg-[#81b622]",
    tabColor: "bg-lime-500",
  },
  {
    id: 12,
    color: "bg-gradient-to-t from-[#fd7f20] via-[#fc2e20] to-[#fdb750]",
    text: "text-white",
    name: "Fiery Blaze",
    linkStyle: "rounded-full",
    shopBox: "rounded-md",
    boxColor: "bg-[#010100]",
    hover: "",
    embosedBox: true,
    embosedBoxColor: "bg-[#fdb750]",
    tabColor: "bg-orange-500",
  },
];
